### ISSUE TITLE
Could not find or load main class telegramdecoder.TelegramDecoder

### ISSUE THREAD

**Issue by NiiMiyo** [hauck-jvsh/telegramDecoder#1]
When running `java -jar .\telegramDecoder.jar` at dist folder got the "**Could not find or load main class telegramdecoder.TelegramDecoder**" error. <br>
The [class](https://github.com/hauck-jvsh/telegramDecoder/blob/master/src/telegramdecoder/DecoderTelegram.java) name was *probably* misspelled.

**Comment by hauck-jvsh** [comment]
Actually, this is a library, and you must implement the main class for loading the telegram database and use it only to decode serialized data.
